services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./demo:/app
      - ./deployments:/deployments
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root
    entrypoint: >
      bash -c "
      apt-get update &&
      apt-get install -y maven &&
      chown -R jenkins:jenkins /var/jenkins_home &&
      su jenkins -c '/usr/bin/tini -- /usr/local/bin/jenkins.sh'
      "

  websphere:
    image: openliberty/open-liberty:latest
    container_name: websphere
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./deployments:/config/dropins
    